soc: qcom: rpmh-rsc: Fix compilation after importing LTS 6.6.46@e665991
Accomodate according to upstream change 459f84f8ee8d ("soc: qcom: rpmh-rsc:
Ensure irqs aren't disabled by rpmh_rsc_send_data() callers") to avoid below
errors:

drivers/soc/qcom/rpmh-rsc.c:821:38: error: use of undeclared identifier 'flags'
drivers/soc/qcom/rpmh-rsc.c:864:37: error: use of undeclared identifier 'flags'

Change-Id: Icb367ee05e044403aa2925ec2a5758a68ce949aa
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>